name: Check for last GE update

on:
  #schedule: 
  # Run every 10 minutes
  # - cron: '0/10 * * * *'
  # Run manually from the Actions tab
  workflow_dispatch:

#jobs:
  # This workflow contains a single job called "check_for_updates"
  #check_for_updates:
    # The type of runner that the job will run on
  #  runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
  #    - uses: actions/checkout@v3
      # uses local file
  #    - uses ./updater/check_update_time
      
      # TODO: convert to curl command instead of python script?
      
      # installs python 3.10
  #    - name: setup python 3.10
  #      uses: actions/setup-python@v4
  #      with:
  #        python-version: '3.10' 
      
  #    - name: execute check_update_time script
  #      run: python /updater/check_update_time.py

jobs:
    check_for_updates:
     name: check if update ready
     runs-on: ubuntu-latest
     steps:
       - shell: bash
         run: |
           curl -o last_update_times.json "https://api.weirdgloop.org/exchange"
       - name: Upload result
         uses: actions/upload-artifact@v3
         with:
           name: last_update_times
           path: ./updater/last_update_times.json

  # see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
