name: Check for last GE update

on:
  schedule: 
  # Run every 10 minutes
   - cron: '0/10 * * * *'
  # Run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "check_for_updates"
  check_for_updates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v3

      # TODO: convert to curl command instead of python script?
      
      # installs python 3.10
      - name: setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: execute check_update_time script
        run: python /updater/check_update_time.py

      
