name: Check for last GE update

on:
  #schedule: 
  # Run every 10 minutes
  # - cron: '0/10 * * * *'
  # Run manually from the Actions tab
  workflow_dispatch:
  
jobs:
  check_api_response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup_py
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies (if needed)
        id: setup_dep
        run: |
          pip install requests
        
      - name: Run Python script
        id: run_py
        run: python updater/check_update_time.py
        
      - name: commit any changes from python script
        id: commit_changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A 
          git commit -m "Github Action 'check_for_updates', has updated a file!"
          git push origin main
        
