name: Run updaters

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  # run when specific files are pushed to
  push:
    paths:
      - '/updater/status/*'

  
jobs:
  run_db_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup_py
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies (if needed)
        id: setup_dep
        run: |
          pip install requests
        
      - name: Find and Process "READY" Files 
        run: |
          for file in updater/status/*; do
            if [ -f "$file" ] && [ "$(cat "$file")" = "READY" ]; then
              echo "Processing file: $file"
              python /updater/update_db.py "$file" &
            fi
          done
        
      - name: commit any changes from python script
        id: commit_changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A 
          git commit -m "Github Action 'run_db_updaters', has updated a file!"
          git push origin main
        
